services:
  - type: web
    name: handwritten-prescription-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
