services:
  - type: web
    name: handwritten-prescription-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    pythonVersion: 3.9.13  # ✅ Add this line!
    autoDeploy: true
